const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.bound,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.LOS,
		C3.Behaviors.MoveTo,
		C3.Plugins.progressbar,
		C3.Behaviors.Anchor,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.Camera3D,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Text.Exps.Y,
		C3.Behaviors.MoveTo.Acts.SetSpeed,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.CompareTime
	];
};
self.C3_JsPropNameTable = [
	{NewGame: 0},
	{JudulGame: 0},
	{Mouse: 0},
	{BackgroundNewGame: 0},
	{bghitam: 0},
	{Story: 0},
	{iconPlay: 0},
	{Start: 0},
	{bunga: 0},
	{PohonHitam: 0},
	{NanaHp: 0},
	{canmove: 0},
	{BoundToLayout: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{Nana: 0},
	{Solid: 0},
	{Jalan: 0},
	{Keyboard: 0},
	{Pagar: 0},
	{Bunga2: 0},
	{iscanmove: 0},
	{HP: 0},
	{isattack: 0},
	{isdead: 0},
	{LineOfSight: 0},
	{MoveTo: 0},
	{creature: 0},
	{knife_hit: 0},
	{damage: 0},
	{cakar: 0},
	{HealthBar: 0},
	{Malam: 0},
	{cahaya: 0},
	{ElmwoodForest: 0},
	{Anchor: 0},
	{move: 0},
	{kedamahp: 0},
	{kedama: 0},
	{pixilframe: 0},
	{TiledBackground: 0},
	{play: 0},
	{dark: 0},
	{camerafocus: 0},
	{Jalan2: 0},
	{forest2: 0},
	{ID: 0},
	{Fade: 0},
	{portal2: 0},
	{Sprite2: 0},
	{youdied: 0},
	{iscanmove1: 0},
	{iscanattack1: 0},
	{healthwolf: 0},
	{isdead1: 0},
	{wolf2: 0},
	{removebgpreview: 0},
	{audio: 0},
	{leader: 0},
	{portal3: 0},
	{kepalakedama: 0},
	{Sprite: 0},
	{gamepassed: 0},
	{leftarrow: 0},
	{rightarrow: 0},
	{attackbutton: 0},
	{tombolserang: 0},
	{Touch: 0},
	{tombolserang2: 0},
	{rightarrow2: 0},
	{leftarrow2: 0},
	{NanaHP: 0},
	{NanaMaxHP: 0},
	{rightview: 0},
	{step: 0},
	{firststart: 0},
	{KedamaHp: 0},
	{KedamaMaxHp: 0},
	{IsTextUp: 0}
];

self.InstanceType = {
	NewGame: class extends self.ISpriteInstance {},
	JudulGame: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	BackgroundNewGame: class extends self.ITiledBackgroundInstance {},
	bghitam: class extends self.ITiledBackgroundInstance {},
	Story: class extends self.ITextInstance {},
	iconPlay: class extends self.ISpriteInstance {},
	Start: class extends self.ITextInstance {},
	bunga: class extends self.ISpriteInstance {},
	PohonHitam: class extends self.ISpriteInstance {},
	Nana: class extends self.ISpriteInstance {},
	Jalan: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Pagar: class extends self.ISpriteInstance {},
	Bunga2: class extends self.ISpriteInstance {},
	creature: class extends self.ISpriteInstance {},
	knife_hit: class extends self.ISpriteInstance {},
	cakar: class extends self.ISpriteInstance {},
	HealthBar: class extends self.IProgressBarInstance {},
	Malam: class extends self.ISpriteInstance {},
	cahaya: class extends self.ISpriteInstance {},
	ElmwoodForest: class extends self.ITextInstance {},
	NanaHp: class extends self.ISpriteInstance {},
	kedama: class extends self.ISpriteInstance {},
	pixilframe: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	play: class extends self.ISpriteInstance {},
	dark: class extends self.ITiledBackgroundInstance {},
	camerafocus: class extends self.ISpriteInstance {},
	Jalan2: class extends self.ISpriteInstance {},
	forest2: class extends self.ITiledBackgroundInstance {},
	portal2: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	youdied: class extends self.ISpriteInstance {},
	wolf2: class extends self.ISpriteInstance {},
	removebgpreview: class extends self.ISpriteInstance {},
	audio: class extends self.IInstance {},
	kedamahp: class extends self.ISpriteInstance {},
	leader: class extends self.ISpriteInstance {},
	portal3: class extends self.ISpriteInstance {},
	kepalakedama: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	gamepassed: class extends self.ITextInstance {},
	leftarrow: class extends self.ISpriteInstance {},
	rightarrow: class extends self.ISpriteInstance {},
	attackbutton: class extends self.IInstance {},
	tombolserang: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	tombolserang2: class extends self.ISpriteInstance {},
	rightarrow2: class extends self.ISpriteInstance {},
	leftarrow2: class extends self.ISpriteInstance {}
}